### ISSUE TITLE
Error when ninja : Shape mismatch in assignement

### ISSUE THREAD

**Issue by DbrRoxane** [commonsense/conceptnet-numberbatch#59]
Hi,

When I launch ninja, I get this error 
`[21/127] python3 -m conceptnet_retrofitting.builders.self_loops build...uild-data/glove.840B.300d.ppdb-xl-lexical-standardized.self_loops.npz
FAILED: build-data/glove.840B.300d.ppdb-xl-lexical-standardized.self_loops.npz 
python3 -m conceptnet_retrofitting.builders.self_loops build-data/glove.840B.300d.ppdb-xl-lexical-standardized.npz build-data/glove.840B.300d.ppdb-xl-lexical-standardized.self_loops.npz
Traceback (most recent call last):
  File "/media/data/roxane/anaconda3/envs/numberbatch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/media/data/roxane/anaconda3/envs/numberbatch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/data/roxane/Desktop/conceptnet-numberbatch/code/conceptnet_retrofitting/builders/self_loops.py", line 22, in <module>
    main(*sys.argv[1:])
  File "/media/data/roxane/Desktop/conceptnet-numberbatch/code/conceptnet_retrofitting/builders/self_loops.py", line 16, in main
    assoc = self_loops(assoc)
  File "/media/data/roxane/Desktop/conceptnet-numberbatch/code/conceptnet_retrofitting/builders/self_loops.py", line 8, in self_loops
    assoc[diagonal] = assoc.sum(axis=1).T[0]
  File "/media/data/roxane/anaconda3/envs/numberbatch/lib/python3.7/site-packages/scipy/sparse/_index.py", line 124, in __setitem__
    raise ValueError("shape mismatch in assignment")
ValueError: shape mismatch in assignment
`

I used the orginal datasets and when I debug, I cannot see mismatchh in shape... 
Has anybody else had this issue?

**Comment by rspeer** [comment]
I don't think I'll be able to debug or support this -- this is about the build process for Numberbatch that's been replaced years ago. The new build process is an integrated part of the ConceptNet build, described here: https://github.com/commonsense/conceptnet5/wiki/Build-process
